# This is a basic workflow to help you get started with Actions

name: Utah Avalanche Center

# Controls when the workflow will run
on:
  # Triggers the workflow on every 15 minutes between 5-9 am
  schedule:
    cron: '0,15,30,45 5-9 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Print Time
        run: echo Datetime $(TZ=America/Denver date +%Y-%m-%d---%H:%M:%S)

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
